name: cafe_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  dartz: ^0.10.1
  envied: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.1.2
  google_sign_in: ^6.3.0
  json_annotation: ^4.9.0
  keyboard_dismisser: ^3.0.0
  supabase_flutter: ^2.9.0
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900
